import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Starting database seed...')

  // Clear existing data
  await prisma.menuItem.deleteMany()
  await prisma.menuCategory.deleteMany()
  await prisma.openingHour.deleteMany()
  await prisma.restaurant.deleteMany()

  // Create Demo Bistro & Cafe
  const restaurant = await prisma.restaurant.create({
    data: {
      name: 'Demo Bistro & Cafe',
      slug: 'demo-bistro',
      description: 'Modern bir atmosferde geleneksel ve uluslararası lezzetlerin buluştuğu özel mekan. İstanbul\'un kalbinde, taze ve kaliteli malzemelerle hazırlanan enfes yemekler.',
      primaryColor: '#DC2626',
      secondaryColor: '#991B1B',
      accentColor: '#F87171',
      phone: '+90 212 555 0123',
      address: 'Nişantaşı Mahallesi, Teşvikiye Caddesi No: 42/A, Şişli/İstanbul',
      instagram: '@demobistro',
      wifiName: 'DemoBistro_Guest',
      wifiPassword: 'bistro2024',
      languageDefault: 'tr',
      supportedLanguages: 'tr,en',
    },
  })

  console.log('✅ Created restaurant:', restaurant.name)

  // Create opening hours
  const openingHours = [
    { dayOfWeek: 0, openTime: '10:00', closeTime: '23:00', isClosed: false }, // Sunday
    { dayOfWeek: 1, openTime: '08:00', closeTime: '23:30', isClosed: false }, // Monday
    { dayOfWeek: 2, openTime: '08:00', closeTime: '23:30', isClosed: false }, // Tuesday
    { dayOfWeek: 3, openTime: '08:00', closeTime: '23:30', isClosed: false }, // Wednesday
    { dayOfWeek: 4, openTime: '08:00', closeTime: '23:30', isClosed: false }, // Thursday
    { dayOfWeek: 5, openTime: '08:00', closeTime: '01:00', isClosed: false }, // Friday
    { dayOfWeek: 6, openTime: '10:00', closeTime: '01:00', isClosed: false }, // Saturday
  ]

  for (const hour of openingHours) {
    await prisma.openingHour.create({
      data: {
        ...hour,
        restaurantId: restaurant.id,
      },
    })
  }

  console.log('✅ Created opening hours')

  // Define categories with items
  const categoriesData = [
    {
      slug: 'kahvaltiliklar',
      type: 'food',
      order: 1,
      name_tr: 'Kahvaltılıklar',
      name_en: 'Breakfasts',
      description_tr: 'Güne enerjik başlamanız için özel hazırlanmış kahvaltı seçenekleri',
      description_en: 'Specially prepared breakfast options to start your day energetically',
      icon: 'coffee',
      items: [
        {
          order: 1,
          name_tr: 'Serpme Kahvaltı',
          name_en: 'Traditional Turkish Breakfast',
          description_tr: 'Çeşit çeşit peynir, zeytin, reçel, bal, kaymak, simit, börek, yumurta ve taze sıcak çay ile sunulan zengin kahvaltı tabağı',
          description_en: 'Rich breakfast platter with various cheeses, olives, jam, honey, cream, bagel, pastry, eggs and fresh hot tea',
          price: 280,
          isPopular: true,
          allergens: 'gluten,milk,eggs',
          imageUrl: 'https://images.pexels.com/photos/5638527/pexels-photo-5638527.jpeg',
        },
        {
          order: 2,
          name_tr: 'Menemen',
          name_en: 'Turkish Scrambled Eggs',
          description_tr: 'Domates, biber ve soğan ile pişirilmiş geleneksel Türk yumurta yemeği, yanında taze ekmek',
          description_en: 'Traditional Turkish egg dish cooked with tomatoes, peppers and onions, served with fresh bread',
          price: 120,
          isSpicy: true,
          allergens: 'eggs',
          imageUrl: 'https://images.pexels.com/photos/5638364/pexels-photo-5638364.jpeg',
        },
        {
          order: 3,
          name_tr: 'Avokadolu Tost',
          name_en: 'Avocado Toast',
          description_tr: 'Ekşi maya ekmeği üzerinde ezilmiş avokado, poşe yumurta, cherry domates ve susam',
          description_en: 'Mashed avocado on sourdough bread with poached egg, cherry tomatoes and sesame',
          price: 165,
          isVegan: false,
          allergens: 'gluten,eggs',
          imageUrl: 'https://images.pexels.com/photos/566566/pexels-photo-566566.jpeg',
        },
        {
          order: 4,
          name_tr: 'Sağlıklı Granola Bowl',
          name_en: 'Healthy Granola Bowl',
          description_tr: 'Ev yapımı granola, taze mevsim meyveleri, Yunan yoğurdu ve organik bal',
          description_en: 'Homemade granola with fresh seasonal fruits, Greek yogurt and organic honey',
          price: 145,
          isVegan: false,
          allergens: 'milk,nuts',
          imageUrl: 'https://images.pexels.com/photos/1092730/pexels-photo-1092730.jpeg',
        },
        {
          order: 5,
          name_tr: 'Kruvasan Tabağı',
          name_en: 'Croissant Platter',
          description_tr: 'Tereyağlı kruvasan, peynir, salam, taze meyve ve reçel',
          description_en: 'Butter croissant with cheese, salami, fresh fruits and jam',
          price: 155,
          allergens: 'gluten,milk',
          imageUrl: 'https://images.pexels.com/photos/2135677/pexels-photo-2135677.jpeg',
        },
      ],
    },
    {
      slug: 'atistirmaliklar',
      type: 'food',
      order: 2,
      name_tr: 'Atıştırmalıklar',
      name_en: 'Snacks & Appetizers',
      description_tr: 'Paylaşmak için ideal lezzetli atıştırmalıklar',
      description_en: 'Delicious snacks perfect for sharing',
      icon: 'utensils',
      items: [
        {
          order: 1,
          name_tr: 'Crispy Chicken Wings',
          name_en: 'Crispy Chicken Wings',
          description_tr: 'Özel baharatlarla marine edilmiş çıtır tavuk kanatları, ranch sos ve sebze garnitür ile',
          description_en: 'Crispy chicken wings marinated with special spices, served with ranch sauce and vegetable garnish',
          price: 185,
          isPopular: true,
          isSpicy: true,
          allergens: 'milk',
          imageUrl: 'https://images.pexels.com/photos/2313686/pexels-photo-2313686.jpeg',
        },
        {
          order: 2,
          name_tr: 'Mozzarella Sticks',
          name_en: 'Mozzarella Sticks',
          description_tr: 'Çıtır kızarmış mozzarella peyniri çubukları, marinara sos ile',
          description_en: 'Crispy fried mozzarella cheese sticks with marinara sauce',
          price: 140,
          allergens: 'gluten,milk',
          imageUrl: 'https://images.pexels.com/photos/4518656/pexels-photo-4518656.jpeg',
        },
        {
          order: 3,
          name_tr: 'Patates Kızartması',
          name_en: 'French Fries',
          description_tr: 'El yapımı patates kızartması, taze otlar ve özel baharat karışımı ile',
          description_en: 'Handmade french fries with fresh herbs and special spice mix',
          price: 90,
          isVegan: true,
          allergens: '',
          imageUrl: 'https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg',
        },
        {
          order: 4,
          name_tr: 'Soğan Halkaları',
          name_en: 'Onion Rings',
          description_tr: 'Çıtır soğan halkaları, acılı mayonez sos ile',
          description_en: 'Crispy onion rings with spicy mayo sauce',
          price: 110,
          allergens: 'gluten',
          imageUrl: 'https://images.pexels.com/photos/209540/pexels-photo-209540.jpeg',
        },
        {
          order: 5,
          name_tr: 'Nachos Supreme',
          name_en: 'Nachos Supreme',
          description_tr: 'Tortilla cipsi, cheddar peyniri, jalapeño, guacamole, ekşi krema ve salsa sos',
          description_en: 'Tortilla chips with cheddar cheese, jalapeño, guacamole, sour cream and salsa sauce',
          price: 165,
          isSpicy: true,
          allergens: 'milk',
          imageUrl: 'https://images.pexels.com/photos/5710192/pexels-photo-5710192.jpeg',
        },
        {
          order: 6,
          name_tr: 'Karışık Bruschetta',
          name_en: 'Mixed Bruschetta',
          description_tr: 'Kızarmış ekmek üzerinde domates, fesleğen, mozzarella ve zeytinyağı',
          description_en: 'Toasted bread topped with tomato, basil, mozzarella and olive oil',
          price: 135,
          allergens: 'gluten,milk',
          imageUrl: 'https://images.pexels.com/photos/1305063/pexels-photo-1305063.jpeg',
        },
      ],
    },
    {
      slug: 'tacolar',
      type: 'food',
      order: 3,
      name_tr: 'Tacolar',
      name_en: 'Tacos',
      description_tr: 'Meksika mutfağından özgün lezzetler',
      description_en: 'Authentic flavors from Mexican cuisine',
      icon: 'drumstick',
      items: [
        {
          order: 1,
          name_tr: 'Beef Taco',
          name_en: 'Beef Taco',
          description_tr: 'Baharatlı dana eti, marul, domates, cheddar peyniri ve ekşi krema ile yumuşak tortilla',
          description_en: 'Spiced beef with lettuce, tomato, cheddar cheese and sour cream in soft tortilla',
          price: 155,
          isPopular: true,
          allergens: 'gluten,milk',
          imageUrl: 'https://images.pexels.com/photos/4958792/pexels-photo-4958792.jpeg',
        },
        {
          order: 2,
          name_tr: 'Chicken Taco',
          name_en: 'Chicken Taco',
          description_tr: 'Izgara tavuk, avokado, salsa, cheddar ve taze sebzeler',
          description_en: 'Grilled chicken with avocado, salsa, cheddar and fresh vegetables',
          price: 145,
          allergens: 'gluten,milk',
          imageUrl: 'https://images.pexels.com/photos/4958718/pexels-photo-4958718.jpeg',
        },
        {
          order: 3,
          name_tr: 'Fish Taco',
          name_en: 'Fish Taco',
          description_tr: 'Kızarmış balık fileto, lahana salatası, chipotle mayonez ve limon',
          description_en: 'Fried fish fillet with coleslaw, chipotle mayo and lime',
          price: 165,
          allergens: 'gluten,fish,eggs',
          imageUrl: 'https://images.pexels.com/photos/6941020/pexels-photo-6941020.jpeg',
        },
        {
          order: 4,
          name_tr: 'Vegan Taco',
          name_en: 'Vegan Taco',
          description_tr: 'Siyah fasulye, mısır, avokado, salsa ve vegan peynir',
          description_en: 'Black beans, corn, avocado, salsa and vegan cheese',
          price: 135,
          isVegan: true,
          allergens: 'gluten',
          imageUrl: 'https://images.pexels.com/photos/7541800/pexels-photo-7541800.jpeg',
        },
      ],
    },
    {
      slug: 'pizzalar',
      type: 'food',
      order: 4,
      name_tr: 'Pizzalar',
      name_en: 'Pizzas',
      description_tr: 'Taş fırında pişen İtalyan pizzalar',
      description_en: 'Italian pizzas baked in stone oven',
      icon: 'pizza',
      items: [
        {
          order: 1,
          name_tr: 'Margherita Pizza',
          name_en: 'Margherita Pizza',
          description_tr: 'Klasik İtalyan pizzası: domates sos, mozzarella, taze fesleğen ve zeytinyağı',
          description_en: 'Classic Italian pizza: tomato sauce, mozzarella, fresh basil and olive oil',
          price: 195,
          isPopular: true,
          allergens: 'gluten,milk',
          imageUrl: 'https://images.pexels.com/photos/2147491/pexels-photo-2147491.jpeg',
        },
        {
          order: 2,
          name_tr: 'Pepperoni Pizza',
          name_en: 'Pepperoni Pizza',
          description_tr: 'Domates sos, mozzarella peyniri ve bol pepperoni dilimi',
          description_en: 'Tomato sauce, mozzarella cheese and plenty of pepperoni slices',
          price: 215,
          allergens: 'gluten,milk',
          imageUrl: 'https://images.pexels.com/photos/1653877/pexels-photo-1653877.jpeg',
        },
        {
          order: 3,
          name_tr: 'Quattro Formaggi',
          name_en: 'Four Cheese Pizza',
          description_tr: 'Dört peynir pizzası: mozzarella, gorgonzola, parmesan ve ricotta',
          description_en: 'Four cheese pizza: mozzarella, gorgonzola, parmesan and ricotta',
          price: 235,
          allergens: 'gluten,milk',
          imageUrl: 'https://images.pexels.com/photos/3682837/pexels-photo-3682837.jpeg',
        },
        {
          order: 4,
          name_tr: 'Mexicana Pizza',
          name_en: 'Mexicana Pizza',
          description_tr: 'Baharatlı dana eti, jalapeño, mısır, soğan, domates sos ve cheddar',
          description_en: 'Spiced beef, jalapeño, corn, onion, tomato sauce and cheddar',
          price: 225,
          isSpicy: true,
          allergens: 'gluten,milk',
          imageUrl: 'https://images.pexels.com/photos/2216431/pexels-photo-2216431.jpeg',
        },
        {
          order: 5,
          name_tr: 'Veggie Delight',
          name_en: 'Veggie Delight Pizza',
          description_tr: 'Mantar, biber, zeytin, domates, mısır ve mozzarella',
          description_en: 'Mushrooms, peppers, olives, tomatoes, corn and mozzarella',
          price: 205,
          isVegan: false,
          allergens: 'gluten,milk',
          imageUrl: 'https://images.pexels.com/photos/1640772/pexels-photo-1640772.jpeg',
        },
      ],
    },
    {
      slug: 'izgaralar',
      type: 'food',
      order: 5,
      name_tr: 'Izgaralar',
      name_en: 'Grills',
      description_tr: 'Özel marinasyonlarla lezzetlendirilmiş ızgara et çeşitleri',
      description_en: 'Grilled meat varieties flavored with special marinades',
      icon: 'beef',
      items: [
        {
          order: 1,
          name_tr: 'Dana Bonfile',
          name_en: 'Beef Tenderloin',
          description_tr: 'Premium dana bonfile, yanında sebze garnitür, patates püresi ve özel sos',
          description_en: 'Premium beef tenderloin with vegetable garnish, mashed potatoes and special sauce',
          price: 485,
          isPopular: true,
          allergens: 'milk',
          imageUrl: 'https://images.pexels.com/photos/769289/pexels-photo-769289.jpeg',
        },
        {
          order: 2,
          name_tr: 'Kuzu Pirzola',
          name_en: 'Lamb Chops',
          description_tr: 'Taze baharatlarla marine edilmiş kuzu pirzola, közlenmiş sebzeler ile',
          description_en: 'Lamb chops marinated with fresh herbs, served with grilled vegetables',
          price: 425,
          allergens: '',
          imageUrl: 'https://images.pexels.com/photos/3535383/pexels-photo-3535383.jpeg',
        },
        {
          order: 3,
          name_tr: 'Tavuk Şiş',
          name_en: 'Chicken Shish',
          description_tr: 'Özel baharatlarla marine tavuk göğsü, pilav ve salata ile',
          description_en: 'Chicken breast marinated with special spices, served with rice and salad',
          price: 245,
          allergens: '',
          imageUrl: 'https://images.pexels.com/photos/2338407/pexels-photo-2338407.jpeg',
        },
        {
          order: 4,
          name_tr: 'Izgara Köfte',
          name_en: 'Grilled Meatballs',
          description_tr: 'Ev yapımı köfte, közlenmiş domates ve biber, yanında bulgur pilavı',
          description_en: 'Homemade meatballs with grilled tomato and pepper, served with bulgur pilaf',
          price: 215,
          allergens: 'gluten',
          imageUrl: 'https://images.pexels.com/photos/6646600/pexels-photo-6646600.jpeg',
        },
        {
          order: 5,
          name_tr: 'Karışık Izgara',
          name_en: 'Mixed Grill',
          description_tr: 'Tavuk, dana, kuzu ve köfte karışımı, pilav ve cacık ile',
          description_en: 'Mix of chicken, beef, lamb and meatballs with rice and tzatziki',
          price: 395,
          isPopular: true,
          allergens: 'milk',
          imageUrl: 'https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg',
        },
      ],
    },
    {
      slug: 'deniz-urunleri',
      type: 'food',
      order: 6,
      name_tr: 'Deniz Ürünleri',
      name_en: 'Seafood',
      description_tr: 'Taze deniz ürünlerinden özel tarifler',
      description_en: 'Special recipes from fresh seafood',
      icon: 'fish',
      items: [
        {
          order: 1,
          name_tr: 'Izgara Levrek',
          name_en: 'Grilled Sea Bass',
          description_tr: 'Taze levrek, zeytinyağı ve limon sosu, yanında mevsim sebzeleri',
          description_en: 'Fresh sea bass with olive oil and lemon sauce, served with seasonal vegetables',
          price: 385,
          isPopular: true,
          allergens: 'fish',
          imageUrl: 'https://images.pexels.com/photos/1395967/pexels-photo-1395967.jpeg',
        },
        {
          order: 2,
          name_tr: 'Karides Güveç',
          name_en: 'Shrimp Casserole',
          description_tr: 'Tereyağlı karides, mantar, domates ve kaşar peyniri ile fırında',
          description_en: 'Shrimp with butter, mushrooms, tomato and kashkaval cheese baked in oven',
          price: 345,
          allergens: 'shellfish,milk',
          imageUrl: 'https://images.pexels.com/photos/2374946/pexels-photo-2374946.jpeg',
        },
        {
          order: 3,
          name_tr: 'Somon Steak',
          name_en: 'Salmon Steak',
          description_tr: 'Izgara somon, limonlu tereyağı sos, patates püresi ve kuşkonmaz',
          description_en: 'Grilled salmon with lemon butter sauce, mashed potatoes and asparagus',
          price: 365,
          allergens: 'fish,milk',
          imageUrl: 'https://images.pexels.com/photos/1516415/pexels-photo-1516415.jpeg',
        },
        {
          order: 4,
          name_tr: 'Kalamar Tava',
          name_en: 'Fried Calamari',
          description_tr: 'Çıtır kalamar halkası, tarator sos ve roka salatası ile',
          description_en: 'Crispy calamari rings with tartar sauce and arugula salad',
          price: 285,
          allergens: 'shellfish,gluten,eggs',
          imageUrl: 'https://images.pexels.com/photos/6107787/pexels-photo-6107787.jpeg',
        },
      ],
    },
    {
      slug: 'tatlilar',
      type: 'food',
      order: 7,
      name_tr: 'Tatlılar',
      name_en: 'Desserts',
      description_tr: 'Özel yapım tatlılar ve pastalar',
      description_en: 'Specially made desserts and cakes',
      icon: 'cake',
      items: [
        {
          order: 1,
          name_tr: 'San Sebastian Cheesecake',
          name_en: 'San Sebastian Cheesecake',
          description_tr: 'Karamelize yüzeyli, kremsi dokusu ile ünlü Bask cheesecake',
          description_en: 'Famous Basque cheesecake with caramelized surface and creamy texture',
          price: 165,
          isPopular: true,
          allergens: 'milk,eggs',
          imageUrl: 'https://images.pexels.com/photos/5949901/pexels-photo-5949901.jpeg',
        },
        {
          order: 2,
          name_tr: 'Çikolatalı Sufle',
          name_en: 'Chocolate Soufflé',
          description_tr: 'Sıcak çikolata sufle, vanilyalı dondurma ve çilek sos ile',
          description_en: 'Hot chocolate soufflé with vanilla ice cream and strawberry sauce',
          price: 155,
          allergens: 'milk,eggs,gluten',
          imageUrl: 'https://images.pexels.com/photos/1120970/pexels-photo-1120970.jpeg',
        },
        {
          order: 3,
          name_tr: 'Tiramisu',
          name_en: 'Tiramisu',
          description_tr: 'Geleneksel İtalyan tatlısı: mascarpone, kahve ve kakao',
          description_en: 'Traditional Italian dessert: mascarpone, coffee and cocoa',
          price: 145,
          allergens: 'milk,eggs,gluten',
          imageUrl: 'https://images.pexels.com/photos/6880219/pexels-photo-6880219.jpeg',
        },
        {
          order: 4,
          name_tr: 'Magnolia',
          name_en: 'Magnolia Pudding',
          description_tr: 'Ev yapımı sütlü magnolia, karamel sos ve kırık fındık',
          description_en: 'Homemade magnolia pudding with caramel sauce and crushed hazelnuts',
          price: 135,
          allergens: 'milk,nuts',
          imageUrl: 'https://images.pexels.com/photos/3893568/pexels-photo-3893568.jpeg',
        },
        {
          order: 5,
          name_tr: 'Vegan Brownie',
          name_en: 'Vegan Brownie',
          description_tr: 'Vegan çikolatalı brownie, hindistancevizi kreması ve taze meyveler',
          description_en: 'Vegan chocolate brownie with coconut cream and fresh fruits',
          price: 140,
          isVegan: true,
          allergens: 'gluten,nuts',
          imageUrl: 'https://images.pexels.com/photos/2144112/pexels-photo-2144112.jpeg',
        },
        {
          order: 6,
          name_tr: 'Profiterol',
          name_en: 'Profiteroles',
          description_tr: 'Mini profiteroller, krema dolgulu, sıcak çikolata sos ile',
          description_en: 'Mini profiteroles filled with cream, served with hot chocolate sauce',
          price: 150,
          allergens: 'milk,eggs,gluten',
          imageUrl: 'https://images.pexels.com/photos/5949890/pexels-photo-5949890.jpeg',
        },
      ],
    },
    {
      slug: 'limonatalar',
      type: 'drink',
      order: 8,
      name_tr: 'Limonatalar',
      name_en: 'Lemonades',
      description_tr: 'Ev yapımı taze limonatalar',
      description_en: 'Homemade fresh lemonades',
      icon: 'glass-water',
      items: [
        {
          order: 1,
          name_tr: 'Klasik Limonata',
          name_en: 'Classic Lemonade',
          description_tr: 'Taze sıkılmış limon, buz ve nane yaprakları',
          description_en: 'Freshly squeezed lemon with ice and mint leaves',
          price: 75,
          isVegan: true,
          allergens: '',
          imageUrl: 'https://images.pexels.com/photos/96974/pexels-photo-96974.jpeg',
        },
        {
          order: 2,
          name_tr: 'Çilekli Limonata',
          name_en: 'Strawberry Lemonade',
          description_tr: 'Taze çilek püresi, limon ve nane',
          description_en: 'Fresh strawberry puree with lemon and mint',
          price: 85,
          isPopular: true,
          isVegan: true,
          allergens: '',
          imageUrl: 'https://images.pexels.com/photos/5946960/pexels-photo-5946960.jpeg',
        },
        {
          order: 3,
          name_tr: 'Lavanta Limonata',
          name_en: 'Lavender Lemonade',
          description_tr: 'Lavanta şurubu, limon ve soda',
          description_en: 'Lavender syrup with lemon and soda',
          price: 90,
          isVegan: true,
          allergens: '',
          imageUrl: 'https://images.pexels.com/photos/2842876/pexels-photo-2842876.jpeg',
        },
        {
          order: 4,
          name_tr: 'Zencefilli Limonata',
          name_en: 'Ginger Lemonade',
          description_tr: 'Taze zencefil, limon, bal ve buz',
          description_en: 'Fresh ginger with lemon, honey and ice',
          price: 85,
          isVegan: false,
          allergens: '',
          imageUrl: 'https://images.pexels.com/photos/1638280/pexels-photo-1638280.jpeg',
        },
      ],
    },
    {
      slug: 'alkolsuz-icecekler',
      type: 'drink',
      order: 9,
      name_tr: 'Alkolsüz İçecekler',
      name_en: 'Non-Alcoholic Drinks',
      description_tr: 'Taze sıkılmış meyve suları ve smoothie çeşitleri',
      description_en: 'Fresh juices and smoothie varieties',
      icon: 'cup-soda',
      items: [
        {
          order: 1,
          name_tr: 'Taze Sıkılmış Portakal Suyu',
          name_en: 'Fresh Orange Juice',
          description_tr: 'Günlük taze sıkılmış portakal suyu',
          description_en: 'Daily fresh squeezed orange juice',
          price: 70,
          isVegan: true,
          allergens: '',
          imageUrl: 'https://images.pexels.com/photos/1435735/pexels-photo-1435735.jpeg',
        },
        {
          order: 2,
          name_tr: 'Detox Green Smoothie',
          name_en: 'Detox Green Smoothie',
          description_tr: 'Ispanak, yeşil elma, muz, zencefil ve limon',
          description_en: 'Spinach, green apple, banana, ginger and lemon',
          price: 95,
          isPopular: true,
          isVegan: true,
          allergens: '',
          imageUrl: 'https://images.pexels.com/photos/1092730/pexels-photo-1092730.jpeg',
        },
        {
          order: 3,
          name_tr: 'Berry Blast Smoothie',
          name_en: 'Berry Blast Smoothie',
          description_tr: 'Karışık orman meyveleri, yoğurt ve bal',
          description_en: 'Mixed berries, yogurt and honey',
          price: 100,
          allergens: 'milk',
          imageUrl: 'https://images.pexels.com/photos/775032/pexels-photo-775032.jpeg',
        },
        {
          order: 4,
          name_tr: 'Iced Tea',
          name_en: 'Iced Tea',
          description_tr: 'Ev yapımı buzlu çay, şeftali aromalı',
          description_en: 'Homemade iced tea with peach flavor',
          price: 65,
          isVegan: true,
          allergens: '',
          imageUrl: 'https://images.pexels.com/photos/1484412/pexels-photo-1484412.jpeg',
        },
        {
          order: 5,
          name_tr: 'Virgin Mojito',
          name_en: 'Virgin Mojito',
          description_tr: 'Nane, limon, şeker ve soda',
          description_en: 'Mint, lime, sugar and soda',
          price: 80,
          isVegan: true,
          allergens: '',
          imageUrl: 'https://images.pexels.com/photos/3323682/pexels-photo-3323682.jpeg',
        },
      ],
    },
    {
      slug: 'sicak-icecekler',
      type: 'drink',
      order: 10,
      name_tr: 'Sıcak İçecekler',
      name_en: 'Hot Drinks',
      description_tr: 'Kahve ve çay çeşitleri',
      description_en: 'Coffee and tea varieties',
      icon: 'coffee',
      items: [
        {
          order: 1,
          name_tr: 'Espresso',
          name_en: 'Espresso',
          description_tr: 'Çift shot espresso',
          description_en: 'Double shot espresso',
          price: 55,
          isVegan: true,
          allergens: '',
          imageUrl: 'https://images.pexels.com/photos/312418/pexels-photo-312418.jpeg',
        },
        {
          order: 2,
          name_tr: 'Cappuccino',
          name_en: 'Cappuccino',
          description_tr: 'Espresso, köpüklü süt ve kakao',
          description_en: 'Espresso with foamy milk and cocoa',
          price: 70,
          isPopular: true,
          allergens: 'milk',
          imageUrl: 'https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg',
        },
        {
          order: 3,
          name_tr: 'Latte',
          name_en: 'Caffe Latte',
          description_tr: 'Espresso ve buharda ısıtılmış süt',
          description_en: 'Espresso with steamed milk',
          price: 75,
          allergens: 'milk',
          imageUrl: 'https://images.pexels.com/photos/1188533/pexels-photo-1188533.jpeg',
        },
        {
          order: 4,
          name_tr: 'Türk Kahvesi',
          name_en: 'Turkish Coffee',
          description_tr: 'Geleneksel Türk kahvesi, lokum ile',
          description_en: 'Traditional Turkish coffee with Turkish delight',
          price: 50,
          isVegan: true,
          allergens: '',
          imageUrl: 'https://images.pexels.com/photos/4349887/pexels-photo-4349887.jpeg',
        },
        {
          order: 5,
          name_tr: 'Filtre Kahve',
          name_en: 'Filter Coffee',
          description_tr: 'Günün özel filtre kahvesi',
          description_en: 'Specialty filter coffee of the day',
          price: 60,
          isVegan: true,
          allergens: '',
          imageUrl: 'https://images.pexels.com/photos/1251175/pexels-photo-1251175.jpeg',
        },
        {
          order: 6,
          name_tr: 'Sıcak Çikolata',
          name_en: 'Hot Chocolate',
          description_tr: 'Gerçek çikolata, süt ve krem şanti',
          description_en: 'Real chocolate with milk and whipped cream',
          price: 80,
          allergens: 'milk',
          imageUrl: 'https://images.pexels.com/photos/1638730/pexels-photo-1638730.jpeg',
        },
        {
          order: 7,
          name_tr: 'Çay',
          name_en: 'Turkish Tea',
          description_tr: 'Geleneksel demleme Türk çayı',
          description_en: 'Traditional brewed Turkish tea',
          price: 25,
          isVegan: true,
          allergens: '',
          imageUrl: 'https://images.pexels.com/photos/1638280/pexels-photo-1638280.jpeg',
        },
      ],
    },
    {
      slug: 'kokteyller',
      type: 'drink',
      order: 11,
      name_tr: 'Kokteyller',
      name_en: 'Cocktails',
      description_tr: 'El yapımı klasik ve özel kokteyller',
      description_en: 'Handcrafted classic and signature cocktails',
      icon: 'wine',
      items: [
        {
          order: 1,
          name_tr: 'Mojito',
          name_en: 'Mojito',
          description_tr: 'Beyaz rom, taze nane, limon, şeker ve soda',
          description_en: 'White rum, fresh mint, lime, sugar and soda',
          price: 185,
          isPopular: true,
          allergens: '',
          imageUrl: 'https://images.pexels.com/photos/1304540/pexels-photo-1304540.jpeg',
        },
        {
          order: 2,
          name_tr: 'Margarita',
          name_en: 'Margarita',
          description_tr: 'Tekila, triple sec, taze limon suyu ve tuz',
          description_en: 'Tequila, triple sec, fresh lime juice and salt',
          price: 195,
          allergens: '',
          imageUrl: 'https://images.pexels.com/photos/5946970/pexels-photo-5946970.jpeg',
        },
        {
          order: 3,
          name_tr: 'Aperol Spritz',
          name_en: 'Aperol Spritz',
          description_tr: 'Aperol, prosecco, soda ve portakal dilimi',
          description_en: 'Aperol, prosecco, soda and orange slice',
          price: 175,
          allergens: '',
          imageUrl: 'https://images.pexels.com/photos/1405338/pexels-photo-1405338.jpeg',
        },
        {
          order: 4,
          name_tr: 'Cosmopolitan',
          name_en: 'Cosmopolitan',
          description_tr: 'Vodka, triple sec, yaban mersini suyu ve limon',
          description_en: 'Vodka, triple sec, cranberry juice and lime',
          price: 190,
          allergens: '',
          imageUrl: 'https://images.pexels.com/photos/2795026/pexels-photo-2795026.jpeg',
        },
        {
          order: 5,
          name_tr: 'Whiskey Sour',
          name_en: 'Whiskey Sour',
          description_tr: 'Bourbon, taze limon suyu, şeker ve yumurta akı',
          description_en: 'Bourbon, fresh lemon juice, sugar and egg white',
          price: 200,
          allergens: 'eggs',
          imageUrl: 'https://images.pexels.com/photos/1089930/pexels-photo-1089930.jpeg',
        },
      ],
    },
    {
      slug: 'alkollu-icecekler',
      type: 'drink',
      order: 12,
      name_tr: 'Alkollü İçecekler',
      name_en: 'Alcoholic Beverages',
      description_tr: 'Bira, şarap ve diğer alkollü içecekler',
      description_en: 'Beer, wine and other alcoholic drinks',
      icon: 'beer',
      items: [
        {
          order: 1,
          name_tr: 'Efes Pilsen (50cl)',
          name_en: 'Efes Pilsen (50cl)',
          description_tr: 'Yerli bira, soğuk servis',
          description_en: 'Local beer, served cold',
          price: 85,
          isPopular: true,
          allergens: 'gluten',
          imageUrl: 'https://images.pexels.com/photos/1552630/pexels-photo-1552630.jpeg',
        },
        {
          order: 2,
          name_tr: 'Corona Extra (35cl)',
          name_en: 'Corona Extra (35cl)',
          description_tr: 'Meksika birası, limon dilimi ile',
          description_en: 'Mexican beer with lime slice',
          price: 120,
          allergens: 'gluten',
          imageUrl: 'https://images.pexels.com/photos/1089932/pexels-photo-1089932.jpeg',
        },
        {
          order: 3,
          name_tr: 'Şarap - Kırmızı (Kadeh)',
          name_en: 'Red Wine (Glass)',
          description_tr: 'Günün özel kırmızı şarabı',
          description_en: 'Specialty red wine of the day',
          price: 135,
          allergens: 'sulfites',
          imageUrl: 'https://images.pexels.com/photos/1407846/pexels-photo-1407846.jpeg',
        },
        {
          order: 4,
          name_tr: 'Şarap - Beyaz (Kadeh)',
          name_en: 'White Wine (Glass)',
          description_tr: 'Günün özel beyaz şarabı',
          description_en: 'Specialty white wine of the day',
          price: 135,
          allergens: 'sulfites',
          imageUrl: 'https://images.pexels.com/photos/2647933/pexels-photo-2647933.jpeg',
        },
        {
          order: 5,
          name_tr: 'Rakı (Tek)',
          name_en: 'Raki (Single)',
          description_tr: 'Geleneksel Türk rakısı, buzlu servis',
          description_en: 'Traditional Turkish raki, served with ice',
          price: 95,
          allergens: '',
          imageUrl: 'https://images.pexels.com/photos/6151743/pexels-photo-6151743.jpeg',
        },
      ],
    },
  ]

  // Create categories and items
  for (const categoryData of categoriesData) {
    const { items, ...categoryInfo } = categoryData

    const category = await prisma.menuCategory.create({
      data: {
        ...categoryInfo,
        restaurantId: restaurant.id,
      },
    })

    console.log(`✅ Created category: ${category.name_tr}`)

    for (const itemData of items) {
      await prisma.menuItem.create({
        data: {
          ...itemData,
          categoryId: category.id,
        },
      })
    }

    console.log(`   ✅ Created ${items.length} items`)
  }

  console.log('🎉 Seed completed successfully!')
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
